[workspace]
members = [
    "crates/route3_road",
    "crates/s3io",
    "crates/til3serv"
]

[profile.release]
#opt-level = 3
# include full debug info. inceases size of the binary, but that should not matter
# for this tool
debug = 1
# enable lto. increases compilation time
#lto = "fat"
# just few codegen units. slower compilation, but faster code
#codegen-units = 1
