[package]
name = "route3"
version = "0.1.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
osmpbfreader = "0.14.0"
h3ron = "0.10.0"
fast_paths = "0.2.0"
log = "0.4"
env_logger = "0.8"
geo-types = "0.6"
eyre = "0.6"
clap = "^2.33"
toml = "0.5"
flexbuffers = "2.0"

[dependencies.indexmap]
version = "^1"
features = ["serde-1"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.gdal]
version = "0.7.0"
optional = true

[profile.release]
opt-level = 3
# include full debug info. inceases size of the binary, but that should not matter
# for this tool
debug = 2
# enable lto. increases compilation time
lto = true
# just few codegen units. slower compilation, but faster code
codegen-units = 1
