---
bind_to: "127.0.0.1:9001"
s3:
  endpoint: "http://127.0.0.1:9000"
  region: "us-east-1"
  access_key: "admin"
  secret_key: "password"
datasets:
  "pop":
    bucket: "population"
    key_pattern: "{ file_h3_resolution }/{ data_h3_resolution }/{ h3cell }.arrow"
    resolutions:
      # maps "data_h3_resolution" to "file_h3_resolution"
      10: 5

    ## name of the h3index column in the dataset
    ## must be type UInt64
    ## default: "h3index"
    h3index_column_name: "h3index"
