[package]
name = "rout3serv"
version = "0.5.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
publish = false
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = "^3"
env_logger = "0.9"
geo-types = "0.7"
itertools = "0.10"
once_cell = "1"
log = "0.4"
num-traits = "0.2"
ordered-float = "3"
prost = "0.11"
rayon = "^1.5"
regex = "1.5"
serde_yaml = "0.9"
tokio-stream = "0.1"

[dependencies.geo]
version = "0.23"

[dependencies.s3io]
path = "../s3io"

[dependencies.uom]
version = "0.33"
features = ["use_serde"]

[dependencies.mimalloc]
version = "0.1"
default_features = false

[dependencies.h3ron]
version = "0.15"
features = ["use-rayon", "roaring", "use-serde"]

[dependencies.h3ron-graph]
version = "0.4"
features = ["io_gdal", "io_osm", "io_serde_util"]

[dependencies.uuid]
version = "1"
features = ["v4"]

[dependencies.tokio]
version = "1"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.tonic]
version = "0.8"
features = ["gzip"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.geojson]
version = "0.24"
features = ["geo-types"]

[dependencies.gdal]
version = "0.13"
features = ["bindgen"]

[dependencies.tower-http]
version = "^0.3"
features = ["trace"]

[dev-dependencies]
float-cmp = "0.9"

[build-dependencies]
tonic-build = { version = "0.8" }
vergen = { version = "7", features = ["rustc", "build"] }
