[package]
name = "route3_core"
version = "0.1.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
bincode = "1.3"
bytesize = "1"
eyre = "0.6"
geo = "0.18"
geo-types = "0.7"
h3ron = "0.11"
log = "0.4"
pathfinding = "2.1"
serde_json = "1"
toml = "0.5"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.gdal]
version = "0.8.0"
optional = true

