# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='route3.proto',
  package='grpc.route3',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0croute3.proto\x12\x0bgrpc.route3\"\x10\n\x0eVersionRequest\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\xae\x01\n&DisturbanceOfPopulationMovementRequest\x12 \n\x18\x64isturbance_wkb_geometry\x18\x01 \x01(\x0c\x12\x15\n\rradius_meters\x18\x02 \x01(\x01\x12!\n\x19num_destinations_to_reach\x18\x03 \x01(\r\x12(\n\x0c\x64\x65stinations\x18\x04 \x03(\x0b\x32\x12.grpc.route3.Point\"7\n)GetDisturbanceOfPopulationMovementRequest\x12\n\n\x02id\x18\x01 \x01(\t\"b\n$DisturbanceOfPopulationMovementStats\x12%\n\x1dpopulation_within_disturbance\x18\x01 \x01(\x01\x12\x13\n\x0brecordbatch\x18\x02 \x01(\x0c\"w\n\'DisturbanceOfPopulationMovementResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12@\n\x05stats\x18\x02 \x01(\x0b\x32\x31.grpc.route3.DisturbanceOfPopulationMovementStats2\xff\x02\n\x06Route3\x12\x46\n\x07Version\x12\x1b.grpc.route3.VersionRequest\x1a\x1c.grpc.route3.VersionResponse\"\x00\x12\x95\x01\n&AnalyzeDisturbanceOfPopulationMovement\x12\x33.grpc.route3.DisturbanceOfPopulationMovementRequest\x1a\x34.grpc.route3.DisturbanceOfPopulationMovementResponse\"\x00\x12\x94\x01\n\"GetDisturbanceOfPopulationMovement\x12\x36.grpc.route3.GetDisturbanceOfPopulationMovementRequest\x1a\x34.grpc.route3.DisturbanceOfPopulationMovementResponse\"\x00\x62\x06proto3'
)




_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='grpc.route3.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=45,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='grpc.route3.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='grpc.route3.VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=81,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='grpc.route3.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='grpc.route3.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='grpc.route3.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=112,
)


_DISTURBANCEOFPOPULATIONMOVEMENTREQUEST = _descriptor.Descriptor(
  name='DisturbanceOfPopulationMovementRequest',
  full_name='grpc.route3.DisturbanceOfPopulationMovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disturbance_wkb_geometry', full_name='grpc.route3.DisturbanceOfPopulationMovementRequest.disturbance_wkb_geometry', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='radius_meters', full_name='grpc.route3.DisturbanceOfPopulationMovementRequest.radius_meters', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_destinations_to_reach', full_name='grpc.route3.DisturbanceOfPopulationMovementRequest.num_destinations_to_reach', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destinations', full_name='grpc.route3.DisturbanceOfPopulationMovementRequest.destinations', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=289,
)


_GETDISTURBANCEOFPOPULATIONMOVEMENTREQUEST = _descriptor.Descriptor(
  name='GetDisturbanceOfPopulationMovementRequest',
  full_name='grpc.route3.GetDisturbanceOfPopulationMovementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.route3.GetDisturbanceOfPopulationMovementRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=346,
)


_DISTURBANCEOFPOPULATIONMOVEMENTSTATS = _descriptor.Descriptor(
  name='DisturbanceOfPopulationMovementStats',
  full_name='grpc.route3.DisturbanceOfPopulationMovementStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='population_within_disturbance', full_name='grpc.route3.DisturbanceOfPopulationMovementStats.population_within_disturbance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recordbatch', full_name='grpc.route3.DisturbanceOfPopulationMovementStats.recordbatch', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=446,
)


_DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE = _descriptor.Descriptor(
  name='DisturbanceOfPopulationMovementResponse',
  full_name='grpc.route3.DisturbanceOfPopulationMovementResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.route3.DisturbanceOfPopulationMovementResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stats', full_name='grpc.route3.DisturbanceOfPopulationMovementResponse.stats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=567,
)

_DISTURBANCEOFPOPULATIONMOVEMENTREQUEST.fields_by_name['destinations'].message_type = _POINT
_DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE.fields_by_name['stats'].message_type = _DISTURBANCEOFPOPULATIONMOVEMENTSTATS
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['DisturbanceOfPopulationMovementRequest'] = _DISTURBANCEOFPOPULATIONMOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['GetDisturbanceOfPopulationMovementRequest'] = _GETDISTURBANCEOFPOPULATIONMOVEMENTREQUEST
DESCRIPTOR.message_types_by_name['DisturbanceOfPopulationMovementStats'] = _DISTURBANCEOFPOPULATIONMOVEMENTSTATS
DESCRIPTOR.message_types_by_name['DisturbanceOfPopulationMovementResponse'] = _DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.Point)
  })
_sym_db.RegisterMessage(Point)

DisturbanceOfPopulationMovementRequest = _reflection.GeneratedProtocolMessageType('DisturbanceOfPopulationMovementRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISTURBANCEOFPOPULATIONMOVEMENTREQUEST,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.DisturbanceOfPopulationMovementRequest)
  })
_sym_db.RegisterMessage(DisturbanceOfPopulationMovementRequest)

GetDisturbanceOfPopulationMovementRequest = _reflection.GeneratedProtocolMessageType('GetDisturbanceOfPopulationMovementRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDISTURBANCEOFPOPULATIONMOVEMENTREQUEST,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.GetDisturbanceOfPopulationMovementRequest)
  })
_sym_db.RegisterMessage(GetDisturbanceOfPopulationMovementRequest)

DisturbanceOfPopulationMovementStats = _reflection.GeneratedProtocolMessageType('DisturbanceOfPopulationMovementStats', (_message.Message,), {
  'DESCRIPTOR' : _DISTURBANCEOFPOPULATIONMOVEMENTSTATS,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.DisturbanceOfPopulationMovementStats)
  })
_sym_db.RegisterMessage(DisturbanceOfPopulationMovementStats)

DisturbanceOfPopulationMovementResponse = _reflection.GeneratedProtocolMessageType('DisturbanceOfPopulationMovementResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE,
  '__module__' : 'route3_pb2'
  # @@protoc_insertion_point(class_scope:grpc.route3.DisturbanceOfPopulationMovementResponse)
  })
_sym_db.RegisterMessage(DisturbanceOfPopulationMovementResponse)



_ROUTE3 = _descriptor.ServiceDescriptor(
  name='Route3',
  full_name='grpc.route3.Route3',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=570,
  serialized_end=953,
  methods=[
  _descriptor.MethodDescriptor(
    name='Version',
    full_name='grpc.route3.Route3.Version',
    index=0,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeDisturbanceOfPopulationMovement',
    full_name='grpc.route3.Route3.AnalyzeDisturbanceOfPopulationMovement',
    index=1,
    containing_service=None,
    input_type=_DISTURBANCEOFPOPULATIONMOVEMENTREQUEST,
    output_type=_DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDisturbanceOfPopulationMovement',
    full_name='grpc.route3.Route3.GetDisturbanceOfPopulationMovement',
    index=2,
    containing_service=None,
    input_type=_GETDISTURBANCEOFPOPULATIONMOVEMENTREQUEST,
    output_type=_DISTURBANCEOFPOPULATIONMOVEMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTE3)

DESCRIPTOR.services_by_name['Route3'] = _ROUTE3

# @@protoc_insertion_point(module_scope)
