[package]
name = "route3"
version = "0.1.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
osmpbfreader = "0.14.0"
h3ron = "0.11.0"
fast_paths = "0.2.0"
log = "0.4"
env_logger = "0.8"
geo-types = "0.7"
geo = "0.18"
eyre = "0.6"
clap = "^2.33"
toml = "0.5"
flexbuffers = "2.0"

[dependencies.indexmap]
version = "^1"
features = ["serde-1"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.gdal]
version = "0.8.0"
optional = true

[dependencies.geojson]
version = "0.22"
features = ["geo-types"]
