bind_to = "0.0.0.0:7088"

[s3]
endpoint = "http://127.0.0.1:9000"
region = "us-east-1"
access_key = "admin"
secret_key = "password"

[graph]
bucket = "graph"
key = "germany_r10.fxb"

[population_dataset]
bucket = "population"
key_pattern = "{ file_h3_resolution }/{ data_h3_resolution }/{ h3cell }.arrow"
file_h3_resolution = 5
