bind_to = "0.0.0.0:7088"

[s3]
endpoint = "http://127.0.0.1:9000"
region = "us-east-1"
access_key = "admin"
secret_key = "password"

[graph]
bucket = "graph"
key = "germany_r10.bc"

[population_dataset]
bucket = "population"
key_pattern = "{ file_h3_resolution }/{ data_h3_resolution }/{ h3cell }.arrow"
file_h3_resolution = 5

## name of the h3index column in the dataset
## must be type UInt64
## default: "h3index"
# h3index_column_name = "h3index"

## name of the population count column in the dataset
## must be type Float32
## default: "population"
# population_count_column_name = "population"


[output]
bucket = "outputs"
key_prefix = "out-"
