[package]
name = "til3serv"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "^0.4"
clap = "^2.33"
env_logger = "0.9"
eyre = "0.6"
geo = "0.18"
geo-types = "^0.7"
lazy_static = "1.4"
log = "0.4"
regex = "1.5"
serde_yaml = "^0.8"

[dependencies.minijinja]
version = "^0.8"
features = ["builtin_filters", "json"]

[dependencies.tokio]
version = "1"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.h3ron]
#version = "0.13"
git = "https://github.com/nmandery/h3ron.git"
rev = "04687ea6c93ebb3bff49b4d398a80c3901180674"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.polars-core]
version = "0.18"
features = ["serde"]

[dependencies.polars-io]
version = "0.18"
features = ["ipc", "json", "parquet", "csv-file", "csv-core"]

[dependencies.tower-http]
version = "^0.2"
features = ["compression-full", "trace"]

[dependencies.s3io]
path = "../s3io"

[build-dependencies]
vergen = { version = "6", features = ["rustc", "build"] }
