---
#bind_to: "127.0.0.1:9001"
bind_to: "0.0.0.0:9001"

# value for the cache-control header. Defaults to `no-cache` when not set.
cache_control: "max-age=3600"

ui:
  enable_ui: true
  base_layer: eoc-baseoverlay

s3:
  endpoint: "http://127.0.0.1:9000"
  region: "us-east-1"
  access_key: "admin"
  secret_key: "password"
datasets:
  "pop":
    bucket: "population"
    key_pattern: "{ file_h3_resolution }/{ data_h3_resolution }/{ h3cell }.arrow"
    resolutions:
      # maps "data_h3_resolution" to "file_h3_resolution"
      10: 5

    ## name of the h3index column in the dataset
    ## must be type UInt64
    ## default: "h3index"
    h3index_column_name: "h3index"

    # optional styling for the tileset in the integrated viewer
    style:
      # property used for styling
      property_name: "population"

      # the value range to apply the colors to
      value_range: [0, 250]

      # the colors for the range. can be anything d3 understands
      color_range: ["white", "green"]
