# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import route3_road_pb2 as route3__road__pb2


class Route3RoadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/route3.road.Route3Road/Version',
                request_serializer=route3__road__pb2.Empty.SerializeToString,
                response_deserializer=route3__road__pb2.VersionResponse.FromString,
                )
        self.ListGraphs = channel.unary_unary(
                '/route3.road.Route3Road/ListGraphs',
                request_serializer=route3__road__pb2.Empty.SerializeToString,
                response_deserializer=route3__road__pb2.ListGraphsResponse.FromString,
                )
        self.ListDatasets = channel.unary_unary(
                '/route3.road.Route3Road/ListDatasets',
                request_serializer=route3__road__pb2.Empty.SerializeToString,
                response_deserializer=route3__road__pb2.ListDatasetsResponse.FromString,
                )
        self.H3ShortestPath = channel.unary_stream(
                '/route3.road.Route3Road/H3ShortestPath',
                request_serializer=route3__road__pb2.H3ShortestPathRequest.SerializeToString,
                response_deserializer=route3__road__pb2.ArrowRecordBatch.FromString,
                )
        self.H3ShortestPathRoutes = channel.unary_stream(
                '/route3.road.Route3Road/H3ShortestPathRoutes',
                request_serializer=route3__road__pb2.H3ShortestPathRequest.SerializeToString,
                response_deserializer=route3__road__pb2.RouteWKB.FromString,
                )
        self.H3ShortestPathCells = channel.unary_stream(
                '/route3.road.Route3Road/H3ShortestPathCells',
                request_serializer=route3__road__pb2.H3ShortestPathRequest.SerializeToString,
                response_deserializer=route3__road__pb2.RouteH3Indexes.FromString,
                )
        self.H3ShortestPathEdges = channel.unary_stream(
                '/route3.road.Route3Road/H3ShortestPathEdges',
                request_serializer=route3__road__pb2.H3ShortestPathRequest.SerializeToString,
                response_deserializer=route3__road__pb2.RouteH3Indexes.FromString,
                )
        self.DifferentialShortestPath = channel.unary_stream(
                '/route3.road.Route3Road/DifferentialShortestPath',
                request_serializer=route3__road__pb2.DifferentialShortestPathRequest.SerializeToString,
                response_deserializer=route3__road__pb2.ArrowRecordBatch.FromString,
                )
        self.GetDifferentialShortestPath = channel.unary_stream(
                '/route3.road.Route3Road/GetDifferentialShortestPath',
                request_serializer=route3__road__pb2.IdRef.SerializeToString,
                response_deserializer=route3__road__pb2.ArrowRecordBatch.FromString,
                )
        self.GetDifferentialShortestPathRoutes = channel.unary_stream(
                '/route3.road.Route3Road/GetDifferentialShortestPathRoutes',
                request_serializer=route3__road__pb2.DifferentialShortestPathRoutesRequest.SerializeToString,
                response_deserializer=route3__road__pb2.DifferentialShortestPathRoutes.FromString,
                )


class Route3RoadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Version(self, request, context):
        """general methods -------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGraphs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def H3ShortestPath(self, request, context):
        """shortest path 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def H3ShortestPathRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def H3ShortestPathCells(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def H3ShortestPathEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DifferentialShortestPath(self, request, context):
        """* differential shortest path based on the population dataset 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDifferentialShortestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDifferentialShortestPathRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Route3RoadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=route3__road__pb2.Empty.FromString,
                    response_serializer=route3__road__pb2.VersionResponse.SerializeToString,
            ),
            'ListGraphs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGraphs,
                    request_deserializer=route3__road__pb2.Empty.FromString,
                    response_serializer=route3__road__pb2.ListGraphsResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=route3__road__pb2.Empty.FromString,
                    response_serializer=route3__road__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'H3ShortestPath': grpc.unary_stream_rpc_method_handler(
                    servicer.H3ShortestPath,
                    request_deserializer=route3__road__pb2.H3ShortestPathRequest.FromString,
                    response_serializer=route3__road__pb2.ArrowRecordBatch.SerializeToString,
            ),
            'H3ShortestPathRoutes': grpc.unary_stream_rpc_method_handler(
                    servicer.H3ShortestPathRoutes,
                    request_deserializer=route3__road__pb2.H3ShortestPathRequest.FromString,
                    response_serializer=route3__road__pb2.RouteWKB.SerializeToString,
            ),
            'H3ShortestPathCells': grpc.unary_stream_rpc_method_handler(
                    servicer.H3ShortestPathCells,
                    request_deserializer=route3__road__pb2.H3ShortestPathRequest.FromString,
                    response_serializer=route3__road__pb2.RouteH3Indexes.SerializeToString,
            ),
            'H3ShortestPathEdges': grpc.unary_stream_rpc_method_handler(
                    servicer.H3ShortestPathEdges,
                    request_deserializer=route3__road__pb2.H3ShortestPathRequest.FromString,
                    response_serializer=route3__road__pb2.RouteH3Indexes.SerializeToString,
            ),
            'DifferentialShortestPath': grpc.unary_stream_rpc_method_handler(
                    servicer.DifferentialShortestPath,
                    request_deserializer=route3__road__pb2.DifferentialShortestPathRequest.FromString,
                    response_serializer=route3__road__pb2.ArrowRecordBatch.SerializeToString,
            ),
            'GetDifferentialShortestPath': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDifferentialShortestPath,
                    request_deserializer=route3__road__pb2.IdRef.FromString,
                    response_serializer=route3__road__pb2.ArrowRecordBatch.SerializeToString,
            ),
            'GetDifferentialShortestPathRoutes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDifferentialShortestPathRoutes,
                    request_deserializer=route3__road__pb2.DifferentialShortestPathRoutesRequest.FromString,
                    response_serializer=route3__road__pb2.DifferentialShortestPathRoutes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'route3.road.Route3Road', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Route3Road(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/route3.road.Route3Road/Version',
            route3__road__pb2.Empty.SerializeToString,
            route3__road__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListGraphs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/route3.road.Route3Road/ListGraphs',
            route3__road__pb2.Empty.SerializeToString,
            route3__road__pb2.ListGraphsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/route3.road.Route3Road/ListDatasets',
            route3__road__pb2.Empty.SerializeToString,
            route3__road__pb2.ListDatasetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def H3ShortestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/H3ShortestPath',
            route3__road__pb2.H3ShortestPathRequest.SerializeToString,
            route3__road__pb2.ArrowRecordBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def H3ShortestPathRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/H3ShortestPathRoutes',
            route3__road__pb2.H3ShortestPathRequest.SerializeToString,
            route3__road__pb2.RouteWKB.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def H3ShortestPathCells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/H3ShortestPathCells',
            route3__road__pb2.H3ShortestPathRequest.SerializeToString,
            route3__road__pb2.RouteH3Indexes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def H3ShortestPathEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/H3ShortestPathEdges',
            route3__road__pb2.H3ShortestPathRequest.SerializeToString,
            route3__road__pb2.RouteH3Indexes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DifferentialShortestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/DifferentialShortestPath',
            route3__road__pb2.DifferentialShortestPathRequest.SerializeToString,
            route3__road__pb2.ArrowRecordBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDifferentialShortestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/GetDifferentialShortestPath',
            route3__road__pb2.IdRef.SerializeToString,
            route3__road__pb2.ArrowRecordBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDifferentialShortestPathRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/route3.road.Route3Road/GetDifferentialShortestPathRoutes',
            route3__road__pb2.DifferentialShortestPathRoutesRequest.SerializeToString,
            route3__road__pb2.DifferentialShortestPathRoutes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
