[package]
name = "slippymap-h3-tiles"
description = "correlating h3 cells into a spherical mercator slippy map tile grid"
authors = ["Nico Mandery <nico@nmandery.net>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
geo = "0.18"
geo-types = "^0.7"

[dependencies.h3ron]
#version = "0.14"
git = "https://github.com/nmandery/h3ron.git"
rev = "321de12b393331072737df1e16f853368b78d9b5"
