[package]
name = "route3_road"
version = "0.3.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
backoff = { version = "0.3", features = ["tokio_1", "futures", "tokio"] }
bytesize = "1"
clap = "^2.33"
env_logger = "0.9"
eyre = "0.6"
futures = "0.3"
geo = "0.18"
lazy_static = "1.4"
log = "0.4"
prost = "0.8"
rayon = "^1.5"
regex = "1.5"
rusoto_core = { version = "0.47" }
rusoto_s3 = { version = "0.47" }
toml = "0.5"
tonic = "0.5"
wkb = "0.7"
tokio-stream = "0.1"
itertools = "0.10"
geo-types = "0.7"
lru = "0.7.0"
num-traits = "0.2"
approx = "0.5"

[dependencies.uom]
version = "0.31"
features = ["use_serde"]

[dependencies.polars-core]
version = "0.16.0"
features = ["serde", "dtype-u64"]

[dependencies.arrow2]
version = "0.5.3" # matches version polars-core depends on
features = ["io_ipc"]

[dependencies.bytes]
version = "1"

[dependencies.mimalloc]
version = "0.1"
default_features = false

[dependencies.h3ron]
git = "https://github.com/nmandery/h3ron.git"
rev = "eb54dd85d2da51f4d8079309351f484a04a0979c"
features = ["io", "use-rayon", "use-roaring"]

[dependencies.h3ron-graph]
git = "https://github.com/nmandery/h3ron.git"
rev = "eb54dd85d2da51f4d8079309351f484a04a0979c"
features = ["use-gdal", "osm"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.tokio]
version = "1.12"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.geojson]
version = "0.22"
features = ["geo-types"]

[dependencies.hyper-tls]
version = "0.5.0"

[dependencies.hyper]
version = "0.14"
features = ["client"]

[dependencies.native-tls]
version = "0.2"

[dependencies.gdal]
version = "0.9.0"
features = ["bindgen"]

[build-dependencies]
tonic-build = "0.5"
vergen = { version = "5", features = ["rustc", "build"] }
